import { useEffect, useMemo, useState } from "react";

const blank = { daily_limit: "", approval_above: "", rolling_hour_limit: "", allowed_recipients: "", allowed_start_hour: "", allowed_end_hour: "", per_recipient_daily_limit: "" };
const presets = {
  Balanced: { ...blank, daily_limit: "100", approval_above: "5", rolling_hour_limit: "25" },
  Strict: { ...blank, daily_limit: "50", approval_above: "10", rolling_hour_limit: "10" },
  "No rolling limit": { ...blank, daily_limit: "100", approval_above: "5" },
};
const attackScenarios = {
  "Merchant burst": { name: "merchant burst", amount: "2.50", count: "5", interval_minutes: "2" },
  "Threshold probe": { name: "threshold probe", amount: "4.99", count: "4", interval_minutes: "8" },
  "Slow drip": { name: "slow drip", amount: "1.50", count: "10", interval_minutes: "30" },
};
function policyFromUrl() {
  const params = new URLSearchParams(window.location.search);
  return { ...blank, daily_limit: params.get("daily") || "", approval_above: params.get("approval") || "", rolling_hour_limit: params.get("rolling") || "" };
}

function policyFromForm(values) {
  if (!values.daily_limit || !values.approval_above) throw new Error("Enter both a daily limit and an approval threshold.");
  if ((values.allowed_start_hour === "") !== (values.allowed_end_hour === "")) throw new Error("Enter both a start and end hour, or leave both blank.");
  if (values.allowed_start_hour !== "" && Number(values.allowed_start_hour) >= Number(values.allowed_end_hour)) throw new Error("Start hour must be before end hour.");
  const numbers = [values.daily_limit, values.approval_above, values.rolling_hour_limit, values.allowed_start_hour, values.allowed_end_hour, values.per_recipient_daily_limit].filter(Boolean).map(Number);
  if (numbers.some((value) => value < 0 || Number.isNaN(value))) throw new Error("Limits must be zero or greater.");
  return { daily_limit: Number(values.daily_limit).toFixed(2), approval_above: Number(values.approval_above).toFixed(2), rolling_hour_limit: values.rolling_hour_limit ? Number(values.rolling_hour_limit).toFixed(2) : null, allowed_recipients: values.allowed_recipients ? values.allowed_recipients.split(",").map((item) => item.trim()).filter(Boolean) : null, allowed_start_hour: values.allowed_start_hour === "" ? null : Number(values.allowed_start_hour), allowed_end_hour: values.allowed_end_hour === "" ? null : Number(values.allowed_end_hour), per_recipient_daily_limit: values.per_recipient_daily_limit ? Number(values.per_recipient_daily_limit).toFixed(2) : null };
}
function money(value) { return value == null ? "—" : `$${Number(value).toFixed(2)}`; }
function readableAIAnswer(value) { return String(value).replace(/&#x20;/g, " ").replace(/&nbsp;/g, " ").replace(/\*\*/g, "").replace(/^\s*\*\s+/gm, "• ").trim(); }
async function post(path, body) { const response = await fetch(path, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.detail || `Request failed (HTTP ${response.status}).`); return data; }

function NumericPolicyForm({ values, onChange, prefix, disabled }) {
  const update = (field) => (event) => onChange({ ...values, [field]: event.target.value });
  return <div className="limit-form">
    <label htmlFor={`${prefix}-daily`}>Daily spend limit<input id={`${prefix}-daily`} type="number" min="0" step="0.01" placeholder="$100" value={values.daily_limit} onChange={update("daily_limit")} disabled={disabled} /></label>
    <label htmlFor={`${prefix}-approval`}>Approval required above<input id={`${prefix}-approval`} type="number" min="0" step="0.01" placeholder="$5" value={values.approval_above} onChange={update("approval_above")} disabled={disabled} /></label>
    <label htmlFor={`${prefix}-rolling`}>Rolling hour limit <small>optional</small><input id={`${prefix}-rolling`} type="number" min="0" step="0.01" placeholder="$25" value={values.rolling_hour_limit} onChange={update("rolling_hour_limit")} disabled={disabled} /></label>
    <details className="advanced-controls"><summary>Advanced controls</summary><label htmlFor={`${prefix}-recipients`}>Allowed recipients <small>comma separated</small><input id={`${prefix}-recipients`} type="text" placeholder="merchant, bookstore" value={values.allowed_recipients} onChange={update("allowed_recipients")} disabled={disabled} /></label><div className="hour-row"><label htmlFor={`${prefix}-start`}>Start hour<input id={`${prefix}-start`} type="number" min="0" max="23" placeholder="9" value={values.allowed_start_hour} onChange={update("allowed_start_hour")} disabled={disabled} /></label><label htmlFor={`${prefix}-end`}>End hour<input id={`${prefix}-end`} type="number" min="0" max="23" placeholder="17" value={values.allowed_end_hour} onChange={update("allowed_end_hour")} disabled={disabled} /></label></div><label htmlFor={`${prefix}-recipient-limit`}>Per-recipient daily limit<input id={`${prefix}-recipient-limit`} type="number" min="0" step="0.01" placeholder="$50" value={values.per_recipient_daily_limit} onChange={update("per_recipient_daily_limit")} disabled={disabled} /></label></details>
  </div>;
}

function AttackCard({ attack, expanded, onToggle }) {
  const kind = attack.outcome === "escaped" ? "escape" : attack.outcome;
  return <article className={`attack-card ${kind}`}>
    <button className="attack-toggle" onClick={onToggle} aria-expanded={expanded}><span className="attack-top"><span className="attack-name">{attack.name}</span><span className={`badge ${kind}`}>{attack.outcome}</span></span><p>{attack.explanation}</p><p className="amount">{attack.decisions.length} <span>checks</span></p></button>
    {expanded && <div className="decision-timeline">{attack.decisions.map((decision, index) => { const payment = attack.payments?.[index]; return <div className="decision-row" key={`${attack.name}-${index}`}><span className={`decision-dot ${decision.status}`} /> <span>Payment {index + 1} · {payment ? money(payment.amount) : "amount unavailable"}</span><b>{decision.status}</b>{payment && <time>{new Date(payment.time).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</time>}{decision.reasons.length > 0 && <small>{decision.reasons.join(", ")}</small>}</div>; })}</div>}
  </article>;
}

function riskFor(attacks) {
  const escaped = attacks.filter((item) => item.outcome === "escaped").length;
  const escalated = attacks.filter((item) => item.outcome === "escalated").length;
  const blocked = attacks.filter((item) => item.outcome === "blocked").length;
  return { escaped, escalated, blocked, score: Math.max(0, Math.min(100, escaped * 35 + escalated * 15 - blocked * 5)) };
}

function recommendationsFor(attacks, policy) {
  const recommendations = [];
  if (attacks.some((item) => item.outcome === "escaped")) recommendations.push("Lower the approval threshold or add a tighter rolling-hour limit to stop small payments from bypassing review.");
  if (attacks.some((item) => item.name === "velocity" && item.outcome !== "blocked") && !policy.rolling_hour_limit) recommendations.push("Add a rolling-hour limit to control rapid repeated payments.");
  if (attacks.some((item) => item.name === "split-second" && item.outcome === "escaped")) recommendations.push("Consider cumulative approval rules so several small payments cannot avoid review together.");
  return recommendations;
}

export default function App() {
  const [policy, setPolicy] = useState(policyFromUrl); const [patch, setPatch] = useState(blank); const [currentPolicy, setCurrentPolicy] = useState(null);
  const [attacks, setAttacks] = useState([]); const [diff, setDiff] = useState(null); const [simulation, setSimulation] = useState(null); const [adaptive, setAdaptive] = useState(null); const [multiAgent, setMultiAgent] = useState(null); const [aiResult, setAiResult] = useState(null); const [aiQuestion, setAiQuestion] = useState("Explain these results and suggest the safest next patch."); const [busy, setBusy] = useState(""); const [error, setError] = useState({ policy: "", patch: "", custom: "", simulation: "", ai: "" }); const [custom, setCustom] = useState({ name: "my attack", amount: "2.50", count: "5", interval_minutes: "2" });
  const [dark, setDark] = useState(() => localStorage.getItem("redline-theme") === "dark"); const [filter, setFilter] = useState("all"); const [search, setSearch] = useState(""); const [expanded, setExpanded] = useState(null);
  const [workspaces, setWorkspaces] = useState(() => JSON.parse(localStorage.getItem("redline-workspaces") || '["Personal"]')); const [workspace, setWorkspace] = useState(() => localStorage.getItem("redline-workspace") || "Personal");
  const [history, setHistory] = useState(() => JSON.parse(localStorage.getItem(`redline-history-${localStorage.getItem("redline-workspace") || "Personal"}`) || "[]"));
  useEffect(() => { document.body.classList.toggle("dark", dark); localStorage.setItem("redline-theme", dark ? "dark" : "light"); }, [dark]);
  useEffect(() => { localStorage.setItem(`redline-history-${workspace}`, JSON.stringify(history.slice(0, 10))); localStorage.setItem("redline-workspace", workspace); localStorage.setItem("redline-workspaces", JSON.stringify(workspaces)); }, [history, workspace, workspaces]);
  const risk = useMemo(() => riskFor(attacks), [attacks]); const filteredAttacks = attacks.filter((item) => (filter === "all" || item.outcome === filter || (filter === "escape" && item.outcome === "escaped")) && (!search.trim() || `${item.name} ${item.explanation}`.toLowerCase().includes(search.trim().toLowerCase())));
  const recommendations = useMemo(() => currentPolicy ? recommendationsFor(attacks, currentPolicy) : [], [attacks, currentPolicy]);

  function applyPreset(name) { setPolicy(presets[name]); setError({ ...error, policy: "" }); }
  function applyAttackScenario(name) { setCustom(attackScenarios[name]); setError({ ...error, custom: "" }); }
  function switchWorkspace(name) { setWorkspace(name); setHistory(JSON.parse(localStorage.getItem(`redline-history-${name}`) || "[]")); setAttacks([]); setCurrentPolicy(null); setDiff(null); setSimulation(null); setAdaptive(null); setMultiAgent(null); setAiResult(null); }
  function addWorkspace() { const name = window.prompt("Name this workspace"); if (!name || !name.trim() || workspaces.includes(name.trim())) return; const next = [...workspaces, name.trim()]; setWorkspaces(next); switchWorkspace(name.trim()); }
  function exportReport() { const report = { exported_at: new Date().toISOString(), policy: currentPolicy, risk, attacks, diff }; const blob = new Blob([JSON.stringify(report, null, 2)], { type: "application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "redline-report.json"; link.click(); URL.revokeObjectURL(link.href); }
  async function sharePolicy() { try { const next = policyFromForm(policy); const url = new URL(window.location.href); url.search = new URLSearchParams({ daily: next.daily_limit, approval: next.approval_above, ...(next.rolling_hour_limit ? { rolling: next.rolling_hour_limit } : {}) }).toString(); await navigator.clipboard.writeText(url.toString()); setError({ ...error, policy: "Share link copied to clipboard." }); } catch (err) { setError({ ...error, policy: err.message }); } }
  function restorePolicy(saved) { setPolicy({ ...blank, ...saved }); setDiff(null); setAttacks([]); setCurrentPolicy(null); setError({ ...error, policy: "Policy restored. Run attacks to test it." }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function runAttacks() { setError({ ...error, policy: "" }); setBusy("run"); try { const next = policyFromForm(policy); const result = await post("/run", next); setCurrentPolicy(next); setAttacks(result.attacks); setExpanded(null); setHistory((items) => [{ at: new Date().toISOString(), policy: next, risk: riskFor(result.attacks) }, ...items].slice(0, 10)); } catch (err) { setError({ ...error, policy: err.message }); } finally { setBusy(""); } }
  async function applyPatch() { setError({ ...error, patch: "" }); setBusy("patch"); try { if (!currentPolicy) throw new Error("Run the current policy first, then enter a patch."); const next = policyFromForm(patch); const result = await post("/patch", { old_policy: currentPolicy, new_policy: next }); setDiff(result); setCurrentPolicy(next); const rerun = await post("/run", next); setAttacks(rerun.attacks); } catch (err) { setError({ ...error, patch: err.message }); } finally { setBusy(""); } }
  async function runCustom() { setError({ ...error, custom: "" }); setBusy("custom"); try { if (!currentPolicy) throw new Error("Run a policy first."); const result = await post("/custom-run", { policy: currentPolicy, name: custom.name, amount: Number(custom.amount).toFixed(2), count: Number(custom.count), interval_minutes: Number(custom.interval_minutes) }); setAttacks((items) => [...items, result.attack]); } catch (err) { setError({ ...error, custom: err.message }); } finally { setBusy(""); } }
  async function stressTest() { setError({ ...error, simulation: "" }); setBusy("simulation"); try { if (!currentPolicy) throw new Error("Run a policy first."); setSimulation(await post("/simulate", { policy: currentPolicy, iterations: 100, seed: 42 })); } catch (err) { setError({ ...error, simulation: err.message }); } finally { setBusy(""); } }
  async function adaptiveTest() { setError({ ...error, simulation: "" }); setBusy("adaptive"); try { if (!currentPolicy) throw new Error("Run a policy first."); const result = await post("/adaptive-run", { policy: currentPolicy, starting_amount: "1.00", steps: 12, interval_minutes: 5 }); setAdaptive(result); setAttacks((items) => [...items, result.attack]); } catch (err) { setError({ ...error, simulation: err.message }); } finally { setBusy(""); } }
  async function multiAgentTest() { setError({ ...error, simulation: "" }); setBusy("multi"); try { if (!currentPolicy) throw new Error("Run a policy first."); setMultiAgent(await post("/multi-agent-run", { policy: currentPolicy, agents: 3, payments_per_agent: 5, amount: "2.00", interval_minutes: 5 })); } catch (err) { setError({ ...error, simulation: err.message }); } finally { setBusy(""); } }
  async function askAI() { setError({ ...error, ai: "" }); setBusy("ai"); try { if (!currentPolicy || !attacks.length) throw new Error("Run attacks before asking the AI assistant."); const cleanQuestion = aiQuestion.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim(); setAiResult(await post("/ai/assist", { policy: currentPolicy, attacks, question: cleanQuestion || "Explain these results and suggest the safest next patch." })); } catch (err) { setError({ ...error, ai: err.message }); } finally { setBusy(""); } }

  return <div className="app-shell"><header className="topbar"><a className="brand" href="/" aria-label="Redline home"><span className="brand-mark">R</span><span>REDLINE</span></a><div className="header-actions"><span className="header-note"><span className="status-dot" /> deterministic policy testing</span><select className="workspace-select" value={workspace} onChange={(event) => switchWorkspace(event.target.value)} aria-label="Workspace">{workspaces.map((name) => <option key={name}>{name}</option>)}</select><button className="workspace-add" onClick={addWorkspace} aria-label="Create workspace">+</button><button className="theme-toggle" onClick={() => setDark(!dark)}>{dark ? "☀ Light mode" : "☾ Dark mode"}</button></div></header>
    <main className="shell"><section className="intro"><div><p className="eyebrow">Policy attack simulator</p><h1>Find the line<br /><em>before</em> the spend.</h1></div><p className="intro-copy">Pressure-test an agent’s spending policy with repeatable attacks. See exactly what escapes, escalates, or gets stopped.</p></section>
      <section className="workspace"><div className="panel"><div className="panel-heading"><div><span className="step">01</span><h2>Set Your Policy</h2></div><span className="live-label">POLICY INPUT</span></div><p className="helper">Enter limits as numbers. The rolling-hour limit is optional.</p><div className="preset-row"><span>Preset</span>{Object.keys(presets).map((name) => <button key={name} onClick={() => applyPreset(name)}>{name}</button>)}<button onClick={sharePolicy}>Share link</button></div><NumericPolicyForm values={policy} onChange={setPolicy} prefix="policy" disabled={busy === "run"} /><div className="panel-footer"><span className="hint">No policy words required</span><button className="button primary" onClick={runAttacks} disabled={busy === "run"}>{busy === "run" ? "Running…" : "Run attacks ↗"}</button></div><p className={`error ${error.policy.includes("copied") ? "success-text" : ""}`}>{error.policy}</p></div>
        <div className="results-column"><div className="results-heading"><div><p className="eyebrow">Attack surface</p><h2>What got through?</h2></div><span>{attacks.length ? `${attacks.length} attacks · just now` : "Run attacks to see results"}</span></div>{attacks.length > 0 && <div className="result-toolbar"><div className="filter-row"><input className="attack-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search attacks" aria-label="Search attacks" />{["all", "escape", "escalated", "blocked", "safe"].map((item) => <button className={filter === item ? "active" : ""} key={item} onClick={() => setFilter(item)}>{item}</button>)}</div><div className="report-actions"><button className="export-button" onClick={exportReport}>Export JSON ↓</button><button className="export-button" onClick={() => window.print()}>Print / PDF</button></div></div>}<div className="attack-grid">{filteredAttacks.map((attack) => <AttackCard key={attack.name} attack={attack} expanded={expanded === attack.name} onToggle={() => setExpanded(expanded === attack.name ? null : attack.name)} />)}</div></div></section>
      {attacks.length > 0 && <section className="insight-grid"><div className="insight-card"><p className="eyebrow">Policy health</p><div className="risk-score"><strong>{risk.score}</strong><span>/ 100 risk</span></div><div className="risk-breakdown"><span className="red-text">{risk.escaped} escaped</span><span className="amber-text">{risk.escalated} escalated</span><span className="green-text">{risk.blocked} blocked</span></div><div className="insight-actions"><button className="stress-button" onClick={stressTest} disabled={busy === "simulation"}>{busy === "simulation" ? "Testing 100 patterns…" : "Stress test 100 patterns"}</button><button className="stress-button" onClick={adaptiveTest} disabled={busy === "adaptive"}>{busy === "adaptive" ? "Adapting…" : "Run adaptive attacker"}</button><button className="stress-button" onClick={multiAgentTest} disabled={busy === "multi"}>{busy === "multi" ? "Testing agents…" : "Test 3 shared agents"}</button></div><p className="error">{error.simulation}</p></div><div className="insight-card"><p className="eyebrow">Recommendations</p>{recommendations.length ? <ul>{recommendations.map((item) => <li key={item}>{item}</li>)}</ul> : <p className="muted-copy">No immediate recommendations. All tested attacks are contained.</p>}</div></section>}
      {simulation && <section className="panel simulation-panel"><div className="panel-heading"><div><span className="step">ST</span><h2>Stress test results</h2></div><span className="live-label">SEEDED · {simulation.iterations} PATTERNS</span></div><div className="simulation-grid">{Object.entries(simulation.counts).map(([outcome, count]) => <div className={`simulation-stat ${outcome}`} key={outcome}><strong>{count}</strong><span>{outcome}</span></div>)}</div>{simulation.examples.length > 0 && <div className="simulation-examples"><p className="eyebrow">Notable patterns</p>{simulation.examples.map((example) => <p key={example.name}><b>{example.name}</b> · {example.outcome} · {example.explanation}</p>)}</div>}</section>}
      {adaptive && <section className="panel simulation-panel adaptive-panel"><div className="panel-heading"><div><span className="step">AD</span><h2>Adaptive attacker</h2></div><span className="live-label">OBSERVED RESPONSE LOOP</span></div><p className="helper">The attacker changed its next amount after each policy response.</p><div className="response-strip">{adaptive.observed_responses.map((response, index) => <span key={`${response}-${index}`} className={`response-pill ${response}`}>{index + 1}: {response}</span>)}</div><p className="muted-copy">Strategy: {adaptive.strategy}.</p></section>}
      {adaptive && <section className="panel simulation-panel adaptive-panel"><div className="panel-heading"><div><span className="step">AD</span><h2>Adaptive attacker</h2></div><span className="live-label">OBSERVED RESPONSE LOOP</span></div><p className="helper">The attacker changed its next amount after each policy response.</p><div className="response-strip">{adaptive.observed_responses.map((response, index) => <span key={`${response}-${index}`} className={`response-pill ${response}`}>{index + 1}: {response}</span>)}</div><p className="muted-copy">Strategy: {adaptive.strategy}.</p></section>}
      {multiAgent && <section className="panel simulation-panel"><div className="panel-heading"><div><span className="step">MA</span><h2>Shared-agent results</h2></div><span className="live-label">{multiAgent.shared_payments} SHARED PAYMENTS</span></div><div className="agent-list">{multiAgent.agents.map((agent) => <div className="agent-row" key={agent.name}><b>{agent.name}</b><span className={`badge ${agent.outcome === "escaped" ? "escape" : agent.outcome}`}>{agent.outcome}</span><span>{money(agent.allowed_total)} allowed</span></div>)}</div></section>}
      <section className="panel ai-panel"><div className="panel-heading"><div><span className="step">AI</span><h2>Ask the policy copilot</h2></div><span className="live-label">OPTIONAL ASSISTANCE</span></div><p className="helper">{attacks.length ? "AI can explain the deterministic results and suggest a patch. It never makes the policy decision." : "Run your policy attacks first. The copilot will then explain the results and suggest a safer patch."}</p><div className="ai-row"><textarea value={aiQuestion} onChange={(event) => setAiQuestion(event.target.value)} aria-label="Ask the policy copilot" disabled={!attacks.length} /><button className="button primary" onClick={askAI} disabled={busy === "ai" || !attacks.length}>{busy === "ai" ? "Thinking…" : "Ask AI ↗"}</button></div><p className="error">{error.ai}</p>{aiResult && <div className="ai-answer"><span className="ai-provider">{aiResult.provider}</span><p>{readableAIAnswer(aiResult.answer)}</p><small>Decision source: {aiResult.decision_source}</small></div>}</section>
      <details className="panel patch-panel collapsible-panel"><summary className="collapsible-summary"><div className="panel-heading"><div><span className="step">02</span><h2>Set Your Patch</h2></div><span className="live-label">COMPARE CHANGES</span></div></summary><div className="collapsible-content"><p className="helper">Enter new numbers to compare a revised policy with the last run.</p><div className="patch-row"><NumericPolicyForm values={patch} onChange={setPatch} prefix="patch" disabled={busy === "patch"} /><button className="button secondary" onClick={applyPatch} disabled={busy === "patch"}>{busy === "patch" ? "Applying…" : "Apply patch ↗"}</button></div><p className="error">{error.patch}</p>{diff ? <div className="diff-area"><span className="diff-icon">+</span><div className="diff-content"><strong>{diff.changed_fields.length} policy fields changed · {diff.outcome_changes.length} attacks changed</strong><div className="diff-list">{diff.changed_fields.map((field) => <span className="diff-chip" key={field.field}><b>{field.field.replaceAll("_", " ")}</b> <del>{money(field.old)}</del> → <ins>{money(field.new)}</ins></span>)}{diff.outcome_changes.map((change) => <span className="diff-chip" key={change.name}><b>{change.name}</b> <del>{change.old}</del> → <ins>{change.new}</ins></span>)}</div></div></div> : <div className="diff-area empty"><span className="diff-icon">+</span><div><strong>No patch applied yet</strong><p>Your policy difference and changed attacks will appear here.</p></div></div>}</div></details>
      <details className="panel custom-panel collapsible-panel"><summary className="collapsible-summary"><div className="panel-heading"><div><span className="step">03</span><h2>Build a Custom Attack</h2></div><span className="live-label">YOUR SCENARIO</span></div></summary><div className="collapsible-content"><p className="helper">Start with a scenario, then adjust its numbers before testing.</p><div className="scenario-row"><span>Scenario library</span>{Object.keys(attackScenarios).map((name) => <button key={name} onClick={() => applyAttackScenario(name)}>{name}</button>)}</div><div className="custom-form"><label>Name<input value={custom.name} onChange={(event) => setCustom({ ...custom, name: event.target.value })} /></label><label>Amount<input type="number" min="0" step="0.01" value={custom.amount} onChange={(event) => setCustom({ ...custom, amount: event.target.value })} /></label><label>Payments<input type="number" min="1" max="100" value={custom.count} onChange={(event) => setCustom({ ...custom, count: event.target.value })} /></label><label>Minutes apart<input type="number" min="0" max="1440" value={custom.interval_minutes} onChange={(event) => setCustom({ ...custom, interval_minutes: event.target.value })} /></label><button className="button primary" onClick={runCustom} disabled={busy === "custom"}>{busy === "custom" ? "Testing…" : "Test scenario ↗"}</button></div><p className="error">{error.custom}</p></div></details>
      {history.length > 0 && <details className="panel history-panel collapsible-panel"><summary className="collapsible-summary"><div className="panel-heading"><div><span className="step">04</span><h2>Run History</h2></div><span className="live-label">{history.length} SAVED RUNS</span></div></summary><div className="collapsible-content"><div className="history-actions"><button className="export-button" onClick={() => setHistory([])}>Clear history</button></div><div className="history-list">{history.map((run) => <div className="history-row" key={run.at}><span>{new Date(run.at).toLocaleString()}</span><span>{money(run.policy.daily_limit)} daily · {money(run.policy.approval_above)} approval</span><b>{run.risk.score} risk</b><button className="export-button" onClick={() => restorePolicy(run.policy)}>Load version</button></div>)}</div></div></details>}
    </main><footer><span>REDLINE / POLICY LAB</span><span>Built for safer autonomous spending</span></footer></div>;
}
